#!/usr/bin/env bash

echo "Preparing installation...."
git clone https://github.com/lvvieira/arch-linux-i3.git arch-linux-i3 &> /dev/null

if [[ ! -d /root/arch-linux-i3 ]]; then
  x=0
  while [ $x -le 6 ]
  do
  
    x=$(( $x + 1 ))
    echo "Retrying $x out of 6 ...."
    echo "Preparing installation...."
    git clone https://github.com/lvvieira/arch-linux-i3.git &> /dev/null

    [[ -d /root/arch-linux-i3 ]] && n=7
  
 done
fi

chmod +x /root/arch-linux-i3/archinstall-UEFI.in
/root/arch-linux-i3/archinstall-UEFI.in -o 1
  
