#!/usr/bin/env bash

echo "Preparing installation...."
git clone https://github.com/lvvieira/arch-linux-i3.git arch-linux

if [[ ! -d /root/arch-linux ]]; then
  x=1
  while [ $x -le 6 ]
  do
  
    x=$(( $x + 1 ))
    echo "Retrying $x out of 6 ...."
    echo "Preparing installation...."
    git clone https://github.com/lvvieira/arch-linux-i3.git arch-linux

    [[ -d /root/arch-linux ]] && n=7 || echo "There may be a problem with your internet connection or with GitHub.com servers."
    read -p "Would you like to try again? " tryagain
    [[ "$tryagain" == "y"]] && n=0 || exit 0
  
 done
fi

chmod +x /root/arch-linux-i3/archinstall-UEFI.in
/root/arch-linux-i3/archinstall-UEFI.in -o 1
  
